server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/companies
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      format_sql: true