server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      format_sql: true